version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb-local
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: graylog
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./db:/data/db
            - ./assets:/assets
            - ./starter:/starter
